server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: user-service-users
          uri: lb://user-service
          predicates:
            - Path=/users/**
        - id: user-service-auth
          uri: lb://user-service
          predicates:
            - Path=/api/auth/**
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/products/**
            - Path=/api/products/**
        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/api/cart/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
